server:
  port: 8082
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8083
user:
  name2: tangyinbo
---
spring:
  profiles: prod
server:
  port: 8084
user:
  name2: tangyinbo2
---
spring:
  profiles: default
server:
  port: 80
user:
  name2: tangyinbo3
